@startuml
skinparam linetype ortho
skinparam classAttributeIconSize 0
hide empty members
left to right direction

class Client

class HeroAircraft {
    - {static} instance : HeroAircraft
    - HeroAircraft(...)
    + {static} getInstance() : HeroAircraft
}

Client --> HeroAircraft : getInstance()

note right of HeroAircraft
if (instance == null) {
  // multi-thread: add lock
  instance = new HeroAircraft(...)
}
return instance
end note

@enduml
